[package]
name = "abc-rs"
version = "0.2.1"
edition = "2021"
license = "MIT"
description = "ABC rust bindings"
repository = "https://github.com/gipsyh/abc-rs"
authors = ["Yuheng Su <gipsyh.icu@gmail.com>"]

[dependencies]
aig = { path = "../aig-rs", version = "0.2.1" }
tempfile = "3.10.1"
